### PR TITLE
Update additional config branches for more targeted deployments

### PR DESCRIPTION
**Pull request by jgmize**
Together with https://github.com/mozmeao/snippets-config/pull/26 this gives us an automatically updated master branch while only triggering one deployment at a time.

### CODE REVIEW

**Comment by glogiotatidis** [comment]
This looks good. I want to make myself comfortable with the new ci and possibly fine  tune a few more bits. If you don't mind let's hold changes for a day or two until I wrap my head around this.

**Comment by jpetto** [comment]
@pmac Can you give this (and the related PR) a look over in terms of approach? I think it'd be good to get the team on board with changes from this point forward.

**Comment by pmac** [comment]
Very cool Giorgos!

**Comment by jgmize** [comment]
thanks @glogiotatidis, https://github.com/mozmeao/snippets-config/pull/28 is a much better approach.

**Pull request closed without merging**
