### PR TITLE
Bump flake8 for point release

### PR DESCRIPTION
**Pull request by stephendonner**
@glogiotatidis r?  Sorry, this is getting to be a bit too frequent (note: I don't mind, but I suspect you or others might?)

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@stephendonner did you check if requires.io is an option? [previous discussion](https://github.com/mozmeao/snippets-service/pull/252#issuecomment-318580110). 

If not can we bundle all these PRs into one PR every 2 weeks or so if that's not blocking you?

**Comment by stephendonner** [comment]
@glogiotatidis I've logged in to Requires.io with my GitHub account, but as I'm no longer a GitHub Admin there (for "mozilla", nor for this "mozmeao" organization), I can't see either public or private-repo settings, to know if that's possible, sorry :-\

**Comment by glogiotatidis** [comment]
OK Thanks for trying. I checked and I understand that requires.io will monitor all requirements.txt files it finds in the repo which I don't want.

Maybe we can do these PRs bi-weekly or monthly?

**Comment by stephendonner** [comment]
Let's start with monthly, for now.  Even I got tired of the point-release followups to the point-releases :-\

**Comment by glogiotatidis** [comment]
Great thanks! I'll revisit automation when i'm back from PTO (~end of august)

**Pull request merged**
