### PR TITLE
[Issue #940] Migrate Snippet off DynamicField.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Note: ` 'has_testpilot'` was intentionality not migrated b/c it has been migrated to `has_addon` in the past.

**Comment by glogiotatidis** [comment]
This gets us off Dynamic Field. I still need to fine tune things to migrate to postgres. 

@jgmize if you're in a hurry I suggest that we merge this early next week and we go ahead with mariadb / mysql on GCP for now. If you can wait another week we can get postgres.

**Comment by jgmize** [comment]
Thanks @glogiotatidis. I can wait another week for postgres :)

**Comment by jpetto** [comment]
The code here all looks good, but I haven't tested it locally yet. Been having serious Docker issues today. Sounds like we're waiting for the postgres changes to come in anyway. 😄

**Comment by glogiotatidis** [comment]
Add two new PRs (#955, #956) to make the app completely db agnostic and therefore capable to migrate to pgsql. Even tried sqlite locally and worked fine!

We need to take special care while migrating, I have a detailed migration plan here https://github.com/mozmeao/snippets-service/issues/940#issue-427538060

**Pull request merged**
