### PR TITLE
Use secure same-site cookies for CSRF by default for #767

### PR DESCRIPTION
**Pull request by jgmize**

### CODE REVIEW

**Comment by jgmize** [comment]
The failing check on this PR is odd, as it's for a vulnerability in requests 2.18.4 but we require requests 2.19.1 in https://github.com/mozmeao/snippets-service/blob/master/requirements.txt#L152

**Comment by glogiotatidis** [comment]
Interesting. I remember Session based CSRF being a security suggestion b/c we're using `mozilla.org` subdomains and cookies could be misused to cause trouble. Is this solved by the `same site` directive?

**Comment by jgmize** [comment]
> Interesting. I remember Session based CSRF being a security suggestion b/c we're using mozilla.org subdomains and cookies could be misused to cause trouble. Is this solved by the same site directive?

That's exactly right, and although `same-site` is not supported in older browsers, I believe we can safely expect Mozilla employees using the snippets admin to be running at least the latest release of Firefox, if not Nightly. For more details see https://blog.mozilla.org/security/2018/04/24/same-site-cookies-in-firefox-60/.

**Comment by glogiotatidis** [comment]
OK, let's try this out. Thanks! :cake:

**Pull request merged**
