### PR TITLE
[Issue #779] Update docker development environment.

### PR DESCRIPTION
**Pull request by glogiotatidis**

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@jpetto @metadave here's an refresh on the docs / docker-compose env. 

I couldn't reproduce the error you see in #779 @metadave. 

r? :)

**Comment by metadave** [comment]
I get the same error, and I also see this in the output from `docker-compose up`:

```
db_1   | 181105 14:09:14 [Note] Server socket created on IP: '::'.
db_1   | 181105 14:09:14 [Warning] 'proxies_priv' entry '@% root@90bccdf5fc0c' ignored in --skip-name-resolve mode.
db_1   | 181105 14:09:14 [Note] mysqld: ready for connections.
db_1   | Version: '10.0.36-MariaDB-1~xenial'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
web_1  | Operations to perform:
web_1  |   Apply all migrations: admin, auth, base, contenttypes, product_details, reversion, sessions
web_1  | Running migrations:
web_1  |   No migrations to apply.
web_1  |   Your models have changes that are not yet reflected in a migration, and so won't be applied.
web_1  |   Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
web_1  | CommandError: Werkzeug is required to use runserver_plus.  Please visit http://werkzeug.pocoo.org/ or install via pip. (pip install Werkzeug)snippets-service_web_1 exited with code 1
```

**Comment by metadave** [comment]
I'll play around a bit more and see what's different on my end.

**Comment by jpetto** [comment]
I got this working on my end. I had to:

- `docker rmi` all old associated images (before doing this I was getting many different errors)
- `docker build .` to build the new image

`docker-compose up` ran migrations, so I'm not sure we need step #3. 

Only other small issue was having to confirm the security exception when loading the admin site, as there's no certificate for the local server.

**Comment by metadave** [comment]
ok, it works. I didn't run step 3 per https://github.com/mozmeao/snippets-service/pull/827#issuecomment-435960022, and I was able to login as admin.

**Comment by metadave** [comment]
I'm getting `ModuleNotFoundError: No module named '"product_details'` when running `./manage.py createsuperuser` or  `./bin/run-dev.sh`:
https://gist.github.com/metadave/840e79d85938dbf833f6920880cacc06

I removed all docker images, and ran through the docker-compose rebuild section.

**Comment by glogiotatidis** [comment]
I believe i got it right this time @metadave. apologies for all the back and forth

**Comment by metadave** [comment]
this works for me, thanks so much for writing this up @glogiotatidis!

**Comment by glogiotatidis** [comment]
> this works for me, thanks so much for writing this up @glogiotatidis!

And thanks for your patience! :)

**Pull request merged**
