### PR TITLE
Hiding x button until snippet is hovered over.

### PR DESCRIPTION
**Pull request by ScottDowne**

### CODE REVIEW

**Comment by ScottDowne** [comment]
@glogiotatidis ping on this.

Jean asked if I could create a small patch to hide the x until hover.

**Comment by glogiotatidis** [comment]
I remember that this was explicitly made to always show, after having it to show only on hover. Is this change permanent or an experiment?

**Comment by ScottDowne** [comment]
Jean didn't mention a test. We should double check.

**Comment by jkt230** [comment]
Thanks @ScottDowne - @glogiotatidis The fundraising, Product (and UX) and Lifecycle marketing teams all got together to figure out ways to improve conversion and perception of the Activity Stream snippets (based on engagement and survey results). One of the ways to see if we can improve results is by making the X only appear when it hovers because right now having the X always show kind of invites users to X out right away. 

I've filed a bug for next year with UX team to see if we can design a flow where if a user X out three or more snippets in a row that they'll be shown a prompt that they can turn off snippets in the preference center.

**Comment by ScottDowne** [comment]
@jkt230 thanks, one last point I want to be crystal clear on, did you want this x change across all activity strea snippets, or just fundraising ones?

**Comment by jkt230** [comment]
@ScottDowne on all please, the experience should be consistent.

**Comment by glogiotatidis** [comment]
In prod!

**Pull request merged**
