### PR TITLE
Dockerize tests

### PR DESCRIPTION
**Pull request by stephendonner**
@glogiotatidis @davehunt r?

I know Giorgos will soon be integrating these tests into the canonical testing + deployment pipeline, but thought I'd finish up the work I started, which now runs and passes 🎉

### CODE REVIEW

**Comment by stephendonner** [comment]
I...forgot docs; working on that now, but might not finish until Monday, sorry.

**Comment by stephendonner** [comment]
@glogiotatidis mind doing the merge honors?  Thanks!

**Comment by stephendonner** [comment]
Forgot to include passing-build output, here: https://pastebin.com/tnnjAPYR

**Comment by glogiotatidis** [comment]
thanks! 🍰

**Pull request merged**
