### PR TITLE
[Fix #344] Add filter for bookmarks count

### LINKED ISSUE #344: [new filter] Filter based on bookmarks usage
Currently waiting for information to become available. [Bug 1431470](https://bugzilla.mozilla.org/show_bug.cgi?id=1431470)

### PR DESCRIPTION
**Pull request by pmac**
The choices for the filter in the admin are a total WAG on my part. We'll just have to see what the opinion of the LCM team is on them.

### CODE REVIEW

**Comment by pmac** [comment]
@glogiotatidis I've updated the JS to what I think will work, but I'm still unsure how to run these locally.

**Comment by pmac** [comment]
I also rebased on master and fixed the migration.

**Comment by glogiotatidis** [comment]
> @glogiotatidis I've updated the JS to what I think will work, but I'm still unsure how to run these locally.

This still doesn't work. I also tried with opening a devtools console in about:home and running `setBookmarksCount` manually but the Promise doesn't seem to ever resolve.

I emailed you some info on how to test!

**Comment by pmac** [comment]
Any ideas @k88hudson? We're stuck on this one.

**Comment by glogiotatidis** [comment]
@rlr maybe you can provide some feedback on https://github.com/mozmeao/snippets-service/pull/395#issuecomment-385320405

**Comment by rlr** [comment]
@glogiotatidis @pmac I'll poke at this today to see what's going on.

**Comment by k88hudson** [comment]
Hmm, you're right – it looks like the reply message is getting dispatched but never received by content. 

@rlr it seems that the problem is something to do with `OnlyToOneContent`

**Comment by rlr** [comment]
Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1460119
Patch: https://github.com/mozilla/activity-stream/pull/4145

Was this needed before Firefox 62? 😬

**Comment by glogiotatidis** [comment]
> Was this needed before Firefox 62? grimacing

This was promised for 60 but I guess we missed that train. Can we get it on 61?

**Comment by k88hudson** [comment]
Since the fix for this is only a single line change, this should be OK to uplift to 61. I'll prep the patch for it

**Comment by k88hudson** [comment]
Ok, I've put in the uplift request here: https://bugzilla.mozilla.org/show_bug.cgi?id=1460119 (the fix should also land in nightly by tomorrow). I'll update this bug when uplift has been completed

**Comment by k88hudson** [comment]
Ok, the uplift has been approved (https://hg.mozilla.org/releases/mozilla-beta/rev/43bcbb69db21), so it should be available in 61 beta and 62 nightly right now

**Comment by glogiotatidis** [comment]
Confirmed, I get the number of my bookmarks in dev console with

`gSnippetsMap.getTotalBookmarksCount().then(count => console.log(count));`

**Comment by glogiotatidis** [comment]
Replaced by #627

**Pull request closed without merging**
