### PR TITLE
 Hide snippets when the user disables snippets from the Preferences + small refactor

### LINKED ISSUE #281: Support visually hiding snippets on the current page when `Snippets:Disabled` event is fired
We have recently added an event that triggers when the Snippet being enabled/disabled via the preferences panel. 

Documentation is here:
https://github.com/mozilla/activity-stream/blob/master/docs/v2-system-addon/snippets.md#events

To listen to the event, just listen on the window, i.e.

```js
window.addEventListener("Snippets:Disabled", () => {
  // hide stuff here
});
```
We probably don't want to actually block the currently shown snippet, as the user hasn't specifically indicated they don't want to see that snippet.

### PR DESCRIPTION
**Pull request by glogiotatidis**
Fixes #281 and a small refactor for country code fetching

### CODE REVIEW

**Comment by glogiotatidis** [comment]
@k88hudson would you mind r? thanks!

**Comment by glogiotatidis** [comment]
Friendly ping @k88hudson ?

**Comment by k88hudson** [comment]
R+, looks good to me!

**Comment by glogiotatidis** [comment]
Thanks!

**Pull request merged**
