### PR TITLE
Bump requests to 2.18.2

### PR DESCRIPTION
**Pull request by stephendonner**
@glogiotatidis r?

```
sdonner-17447:requirements sdonner$ git push origin bump-requests
Counting objects: 5, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 436 bytes | 0 bytes/s, done.
Total 5 (delta 3), reused 0 (delta 0)
remote: Resolving deltas: 100% (3/3), completed with 3 local objects.
To https://github.com/stephendonner/snippets-service
 * [new branch]      bump-requests -> bump-requests
sdonner-17447:requirements sdonner$ tox
py27 installed: apipkg==1.4,appdirs==1.4.3,beautifulsoup4==4.6.0,blessings==1.6,execnet==1.4.1,mozlog==3.4,packaging==16.8,py==1.4.33,pyparsing==2.2.0,pytest==3.0.7,pytest-base-url==1.3.0,pytest-html==1.14.2,pytest-metadata==1.5.0,pytest-xdist==1.16.0,requests==2.14.2,six==1.10.0
py27 runtests: PYTHONHASHSEED='398813561'
py27 runtests: commands[0] | pytest --html=results/py27.html --self-contained-html --junit-xml=results/py27.xml --log-raw=results/py27_raw.txt --log-tbpl=results/py27_tbpl.txt
============================= test session starts ==============================
platform darwin -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0 -- /Users/sdonner/snippets-service/tests/.tox/py27/bin/python2.7
cachedir: .cache
metadata: {'Base URL': 'https://snippets.allizom.org', 'Python': '2.7.13', 'Packages': {'pytest': '3.0.7', 'pluggy': '0.4.0', 'py': '1.4.33'}, 'Platform': 'Darwin-17.0.0-x86_64-i386-64bit', 'Plugins': {'base-url': '1.3.0', 'xdist': '1.16.0', 'mozlog': '3.4', 'metadata': '1.5.0', 'html': '1.14.2'}}
baseurl: https://snippets.allizom.org
rootdir: /Users/sdonner/snippets-service/tests, inifile: tox.ini
plugins: xdist-1.16.0, metadata-1.5.0, html-1.14.2, base-url-1.3.0, mozlog-3.4
collected 9 items 

test_snippets.py::TestSnippets::test_snippet_set_present[/3/Firefox/default/default/default/en-US/release/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_snippet_set_present[/3/Firefox/default/default/default/en-US/aurora/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_snippet_set_present[/3/Firefox/default/default/default/en-US/beta/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_all_links[/3/Firefox/default/default/default/en-US/release/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_all_links[/3/Firefox/default/default/default/en-US/aurora/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_all_links[/3/Firefox/default/default/default/en-US/beta/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_that_snippets_are_well_formed_xml[/3/Firefox/default/default/default/en-US/release/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_that_snippets_are_well_formed_xml[/3/Firefox/default/default/default/en-US/aurora/default/default/default/] PASSED
test_snippets.py::TestSnippets::test_that_snippets_are_well_formed_xml[/3/Firefox/default/default/default/en-US/beta/default/default/default/] PASSED

-- generated xml file: /Users/sdonner/snippets-service/tests/results/py27.xml --
- generated html file: /Users/sdonner/snippets-service/tests/results/py27.html -
=========================== 9 passed in 4.99 seconds ===========================
flake8 installed: appdirs==1.4.3,configparser==3.5.0,enum34==1.1.6,flake8==3.3.0,mccabe==0.6.1,packaging==16.8,pycodestyle==2.3.1,pyflakes==1.5.0,pyparsing==2.2.0,six==1.10.0
flake8 runtests: PYTHONHASHSEED='398813561'
flake8 runtests: commands[0] | flake8 .
____________________________________________ summary ____________________________________________
  py27: commands succeeded
  flake8: commands succeeded
  congratulations :)
```

### CODE REVIEW

**Comment by glogiotatidis** [comment]
Thanks!

**Comment by stephendonner** [comment]
(Let me know if these get too pesky, and/or you'd like to set up pyup.io or requires.io (we prefer the former).)

**Comment by glogiotatidis** [comment]
> (Let me know if these get too pesky, and/or you'd like to set up pyup.io or requires.io (we prefer the former).)

We can try to setup requires.io. I'm wondering whether we can make it follow only `tests/*` as I'd prefer not to have it act on other requirements. Can you give it a try?

**Comment by stephendonner** [comment]
@glogiotatidis I've logged in to Requires.io with my GitHub account, but as I'm no longer a GitHub Admin there (for "mozilla", nor for this "mozmeao" organization), I can't see either public or private-repo settings, to know if that's possible, sorry :-\

**Pull request merged**
